


import * as React from "react"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Provider from "./providers";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { SiteHeader } from "@/components/site-header";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import Meteors from "@/components/magicui/meteors";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <Meteors/>
        <Provider attribute="class" defaultTheme="dark" enableSystem >
          <SiteHeader />
          <div className="flex-1">
            {children}
          </div>
          <TailwindIndicator />
          <ReactQueryDevtools initialIsOpen={false} />
        </Provider>
      </body>
    </html>
  );
}
